export const PHOTO_1 = "../app/assets/img/real1.jpg";
export const PHOTO_2 = "../app/assets/img/placeholder2.jpg";
export const LAURELES = "../app/assets/img/laureles.png";
export const BG = "../app/assets/img/bg3.jpg";
export const LUGAR = "JARDIN DE EVENTOS LA FELICIDAD";
export const FRASE = "El amor es el ingrediente secreto de una buena vida, y";
export const FRASE2 = "están emocionados de comenzar una nueva vida juntos llena de amor";
export const FRASE3 = "No importa si tu respuesta es \"sí\" \"no\" o \"tal vez\"";
export const FRASE4 = "Contamos con su puntualidad para vivir este momento tan especial Asegúrate de confirmar antes del 5 de octubre";
export const TELEFONO_WHATSAPP = "5213121541516"; // Configura aquí tu número de WhatsApp con clave de país (ej. 521...)
